# @package agent
_target_: agent.doubledqn.DoubleDQNAgent
name: doubledqn
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
mode: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 128
feature_dim: 50
epsilon_schedule: 'linear(1.0,0.1,100000)'
nstep: 3
batch_size: 1024 # 256 for pixels
init_critic: true
# update_encoder: ${update_encoder}